version: '3.8'

services:
  transcription-service:
    build: .
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL}
      - WHISPER_QUANTIZED=${WHISPER_QUANTIZED}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"